# Generated by Django 2.0.1 on 2018-02-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('DEBT', 'debt'), ('REPAYMENT', 'repayment')], default='DEBT', max_length=10)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
