# Generated by Django 2.0.1 on 2018-02-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(),
        ),
    ]
