# Generated by Django 2.0.1 on 2018-02-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20180205_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='userId',
            new_name='user_id',
        ),
    ]
